accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accountapp.views import AccountUpdateView, AccountDeleteView, AccountCreateView, AccountLoginView, \
    AccountPasswordSearchView, AccountMenuView

app_name = 'accountapp'

urlpatterns = [
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('password_search/', AccountPasswordSearchView.as_view(), name='password_search'),
    path('accountmenu/<int:pk>', AccountMenuView.as_view(), name='accountmenu'),
]

homescreenapp/urls.py
from django.urls import path

from homescreenapp.views import HomeScreenView, TeacherEmployeeView, AboutUsView, ContactView, UserGuideView

app_name = 'homescreenapp'

urlpatterns = [
    path('homescreen/',HomeScreenView.as_view(), name='homescreen'),
    path('userguide/',UserGuideView.as_view(), name='userguide'),
    path('contact/',ContactView.as_view(), name='contact'),
    path('aboutus/',AboutUsView.as_view(), name='aboutus'),
    path('teacheremployee/',TeacherEmployeeView.as_view(), name='teacheremployee'),
]

matched/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('advertisements/', include('advertisementapp.urls')),
    path('homescreens/', include('homescreenapp.urls')),
    path('announcements/', include('announcementapp.urls')),
    path('careers/', include('careerapp.urls')),
    path('scholarships/', include('scholarshipapp.urls')),
    path('baseinformations/', include('baseinformationapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('classmatchs/', include('classmatchapp.urls')),
    path('studymanages/', include('studymanageapp.urls')),
] +static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accountapp/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator, MaxLengthValidator
from django.db import models

class CustomUser(AbstractUser):
    username = models.CharField(max_length=11,validators=[MinLengthValidator(11), MaxLengthValidator(11)],  unique=True, blank=False)
    userrealname = models.CharField(max_length=10, unique=False, blank=False)
    email = models.EmailField(max_length=25, unique=True, blank=False)

    def annonymusname(self):
        string_name = str(self.userrealname)
        return string_name[0] + '*' + string_name[-1]
    def annonymusphone(self):
        string_phone = str(self.username)
        return '010-' + string_phone[0] + '***-***' + string_phone[-1]

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm, UsernameField
from django import forms

from accountapp.models import CustomUser



class AccountLoginForm(AuthenticationForm):
    username = UsernameField(
        label=(""),
        widget=forms.TextInput(attrs={
            'placeholder': '전화번호',
            'class': 'InputfieldBox',
            'autofocus': True
        })
    )
    password = forms.CharField(
        label=(""),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'placeholder': '비밀번호',
            'class': 'InputfieldBox',
            'autocomplete': 'current-password'
        })
    )

class AccountCreateForm(UserCreationForm):
    password1 = forms.CharField(
        label=("비밀번호"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'placeholder': '영문/숫자/특수문자 혼합 8~20자',
            'class': 'InputfieldBox',
            'autocomplete': 'new-password',
        }),
    )

    password2 = forms.CharField(
        label=(""),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'placeholder': "확인을 위해 위와 동일한 비밀번호를 입력해 주세요",
            'class': 'InputfieldBox',
            'autocomplete': 'new-password'
        }),
    )


    class Meta:
        model = CustomUser
        fields = ('username', 'userrealname', 'email', 'password1', 'password2')
        labels = {
            'username': '전화번호',
            'userrealname': '이름',
            'email': '이메일',
        }

        widgets = {
            'username': forms.NumberInput(attrs={'placeholder': '- 제외 전화번호 11자','class': 'InputfieldBox',}),
            'userrealname': forms.TextInput(attrs={'placeholder': '사용자 실명', 'class': 'InputfieldBox',}),
            'email': forms.EmailInput(attrs={'placeholder': '비밀번호 찾기를 위해 정확한 주소를 입력해 주세요', 'class': 'InputfieldBox',}),
        }




class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True
        self.fields['userrealname'].disabled = True
        self.fields['email'].disabled = True
        self.fields['phone_number'].disabled = True
    password1 = forms.CharField(
        label=("비밀번호"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'placeholder': '영문/숫자/특수문자 혼합 8~20자',
            'class': 'InputfieldBox',
            'autocomplete': 'new-password',
        }),
    )

    password2 = forms.CharField(
        label=(""),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'placeholder': "확인을 위해 위와 동일한 비밀번호를 입력해 주세요",
            'class': 'InputfieldBox',
            'autocomplete': 'new-password'
        }),
    )


    class Meta:
        model = CustomUser
        fields = ('username', 'userrealname', 'email', 'password1', 'password2')
        labels = {
            'username': '전화번호',
            'userrealname': '이름',
            'email': '이메일',
        }

        widgets = {
            'username': forms.NumberInput(attrs={'placeholder': '- 제외 전화번호 11자','class': 'InputfieldBox',}),
            'userrealname': forms.TextInput(attrs={'placeholder': '사용자 실명', 'class': 'InputfieldBox',}),
            'email': forms.EmailInput(attrs={'placeholder': '비밀번호 찾기를 위해 정확한 주소를 입력해 주세요', 'class': 'InputfieldBox',}),
        }

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView, DetailView, ListView


from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountLoginForm, AccountCreateForm, AccountUpdateForm
from accountapp.models import CustomUser

has_ownership = [account_ownership_required, login_required]
class AccountLoginView(LoginView):
    form_class = AccountLoginForm
    template_name = 'accountapp/login.html'
    success_url = reverse_lazy('homescreens:homescreen')

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(AccountLoginView, self).dispatch(request, *args, **kwargs)

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form})



class AccountCreateView(CreateView):
    model = CustomUser
    form_class = AccountCreateForm

    template_name = 'accountapp/create.html'
    success_url = reverse_lazy('accountapp:login')
    def form_valid(self, form):
        temp_user= form.save(commit = False)
        temp_user.customuser = self.request.user
        temp_user.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form})

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = CustomUser
    context_object_name = 'target_user'
    form_class= AccountUpdateForm
    success_url= reverse_lazy('accountapp:login')
    template_name = 'accountapp/update.html'

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form})

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = CustomUser
    context_object_name = 'target_user'
    success_url= reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

class AccountPasswordSearchView(View):
    model = CustomUser
    context_object_name = 'target_user'
    success_url= reverse_lazy('accountapp:login')
    template_name = 'accountapp/password_search.html'

class AccountMenuView(DetailView):
    model = CustomUser
    context_object_name = 'target_user'
    template_name = 'accountapp/accountmenu.html'

accountapp/templates/accountapp/accountmenu.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<style>
.MainFrame{
    height:100%;
    margin:0 2% auto 2%;
}

.Header_Hr_Div{
    display:none;
 }

.AccountProfileBox{
    border: 0.3px solid var(--brightgray_text_color);
    border-radius:1rem;
    display:flex;
    flex-direction: row;
    justify-content:flex-start;
    align-items: center;
    padding-left:1rem;
    padding-right:1rem;
    width:100%;
    height:7rem;
    margin-bottom:1rem;
}

.AccountMenuBox{
    border: 0.3px solid var(--brightgray_text_color);
    border-radius:1rem;
    width:100%;
    margin-bottom:1rem;
}

.profilebutton {
    border-radius:1rem;
    display:flex;
    flex-direction: row;
    justify-content:center;
    align-items: center;
    font-size:1.3rem;
    margin-left:auto;
    width:30%;
    height:40%;
    background-color:var(--menu_bg_color);
}

.AccountProfileItemBox_Content{
    display:flex;
    flex-direction: column;
    justify-content:center;
    align-items: flex-start;
    font-size:1.3rem;
    padding-left:1rem;
    color:var(--dark_text_color);
}

.AccountProfileItemBox_Content_phonenumber{
    margin-top:0.3rem;
    font-size:1.2rem;
    color:var(--darkgray_text_color);
}


.AccountMenuItemBox_Title{
    border-radius:1rem;
    display:flex;
    flex-direction: column;
    justify-content:center;
    align-items: flex-start;
    padding-left:1.5rem;
    height:4.5rem;
    font-size:1.4rem;
    color:var(--dark_text_color);
}
.AccountMenuItemBox_Content{
    display:flex;
    flex-direction: row;
    justify-content:space-between;;
    align-items: center;
    padding-left:1.5rem;
    height:4.5rem;
    font-size:1.3rem;
    color:var(--darkgray_text_color);
}

</style>

<header>
      {% include 'header.html' %}
      <div class="Header_Title_Item TitleFont" >
        내 정보
      </div>
</header>
<main>
  <div class="MainFrame">

    <div class="AccountProfileBox">
        <img style="height:5rem; width:5rem;" src='/media/icons/profile.png'>
        <div class="AccountProfileItemBox_Content">
            <span class="TitleFont">{{target_user.userrealname}}</span>
            <span class="AccountProfileItemBox_Content_phonenumber IndexFont">{{target_user.username}}</span>
        </div>
        <div class="profilebutton IndexFont">프로필 보기</div>
    </div>
    <div class="AccountMenuBox IndexFont">
        <div class="AccountMenuItemBox_Title TitleFont">계정</div>
        <a>
            <div class="AccountMenuItemBox_Content">비밀번호변경</div>
        </a>
        <a>
            <div class="AccountMenuItemBox_Content">회원탈퇴</div>
        </a>
        <a>
            <div class="AccountMenuItemBox_Content">로그아웃</div>
        </a>
    </div>
    <div class="AccountMenuBox IndexFont">
        <div class="AccountMenuItemBox_Title TitleFont">이용안내</div>
        <a href="{% url 'homescreenapp:userguide'%}">
            <div class="AccountMenuItemBox_Content">사용 가이드</div>
        </a>
        <a href="{% url 'homescreenapp:aboutus'%}">
            <div class="AccountMenuItemBox_Content">About us</div>
        </a>
        <a>
            <div class="AccountMenuItemBox_Content">공지사항</div>
        </a>
        <a href="{% url 'homescreenapp:contact'%}">
            <div class="AccountMenuItemBox_Content">문의하기</div>
        </a>

    </div>
    <div class="AccountMenuBox IndexFont">
        <div class="AccountMenuItemBox_Title TitleFont">선생님 관련</div>
        <a href="{% url 'homescreenapp:teacheremployee'%}">
            <div class="AccountMenuItemBox_Content">선생님 채용</div>
        </a>
        <a>
            <div class="AccountMenuItemBox_Content">선생님 계정 신청</div>
        </a>
    </div>
    <div class="AccountMenuBox IndexFont">
        <div class="AccountMenuItemBox_Title TitleFont">기타</div>
        <a>
            <div class="AccountMenuItemBox_Content">알림설정</div>
        </a>
        <a>
            <div class="AccountMenuItemBox_Content">서비스 이용약관</div>
        </a>
        <a>
            <div class="AccountMenuItemBox_Content"><span>개인정보 처리</span><span style="margin-right:2rem;">d</span></div>
        </a>
        <a>
            <div class="AccountMenuItemBox_Content">Copyright</div>
        </a>
    </div>


  </div>
</main>
{% endblock %}

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}



<header>
      {% include 'header.html' %}
      <div class="Header_Title_Item TitleFont" >
        회원가입
      </div>
</header>
<main>
  <div class="MainFrame">
      <form action="{% url 'accountapp:create' %}" method="post" >
        <div class="FormContent_Item IndexFont">{% csrf_token %}{% bootstrap_form form %}</div>
        <div class="SubmitButton_Item"> <input type="submit" class="btn SubmitButton IndexFont" value="회원가입"></div>
      </form>
  </div>
</main>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<style>
.MainFrame{
    margin-top:12rem;
}

.Header_Hr_Div{
    display:none;
 }

.Login_Logo{
    zoom: 1.6;
    display: flex;
    flex-direction: row;
    justify-content:center;
    align-items: center;
    margin-bottom:1.5rem;
}





</style>
<header>
      {% include 'header.html' %}
</header>
<main>
  <div class="MainFrame">
      <div class="Login_Logo" >
        {% include 'snippets/Logo_Dark.html' %}
      </div>
      <form action="{% url 'accountapp:login' %}" method="post" >
        <div class="FormContent_Item IndexFont">{% csrf_token %}{% bootstrap_form form %}</div>

        <div class="SubmitButton_Item"> <input type="submit" class="btn SubmitButton IndexFont" value="로그인"></div>

      </form>


  </div>
</main>
{% endblock %}
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" class ='btn rounded-pill col-6 mt-3 Korean_font2' style="background-color: #f88;">
    </form>

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<style>
.MainFrame{
    margin-top:12rem;
}

.Header_Hr_Div{
    display:none;
 }

.Login_Logo{
    zoom: 1.6;
    display: flex;
    flex-direction: row;
    justify-content:center;
    align-items: center;
    margin-bottom:1.5rem;
}


.SubmitButton_Item{
    margin-top:20rem;
}

.Login_Footer{
    display: flex;
    flex-direction: column;
    justify-content:center;
    align-items: center;
    margin-top:2rem;
    color: var(--darkgray_text_color);
    font-size:1.2rem;
}


</style>
<header>
      {% include 'header.html' %}
</header>
<main>
  <div class="MainFrame">
      <div class="Login_Logo" >
        {% include 'snippets/Logo_Dark.html' %}
      </div>
      <form action="{% url 'accountapp:login' %}" method="post" >
        <div class="FormContent_Item IndexFont">{% csrf_token %}{% bootstrap_form form %}</div>
            <div class="Login_Footer IndexFont">
                <span>비밀번호를 잊어버리셨나요? <a href="{% url 'accountapp:password_search' %}">비밀번호 찾기</a> </span>
                <span>아직 계정이 없으신가요?<a href="{% url 'accountapp:create' %}" >회원가입</a></span>
            </div>
        <div class="SubmitButton_Item"> <input type="submit" class="btn SubmitButton IndexFont" value="로그인"></div>

      </form>


  </div>
</main>
{% endblock %}

accountapp/templates/accountapp/logout.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<style>
    .MainFrame{
        margin-top:15rem;
    }
</style>
<header>
      {% include 'header.html' %}
      <div class="Header_Title_Item TitleFont" >
        로그인
      </div>
</header>
<main>
  <div class="MainFrame">
      <form action="{% url 'accountapp:login' %}" method="post" >
        <div class="FormContent_Item IndexFont">{% csrf_token %}{% bootstrap_form form %}</div>
        <div class="SubmitButton_Item"> <input type="submit" class="btn SubmitButton IndexFont"></div>
      </form>
  </div>
</main>
{% endblock %}

accountapp/templates/accountapp/password_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<header>
      {% include 'header.html' %}
      <div class="Header_Title_Item TitleFont" >
        비밀번호 변경
      </div>
</header>
<main>
  <div class="MainFrame">
      <form action="{% url 'accountapp:update' pk=user.pk %}" method="post" >
        <div class="FormContent_Item IndexFont">{% csrf_token %}{% bootstrap_form form %}</div>
        <div class="SubmitButton_Item"> <input type="submit" class="btn SubmitButton IndexFont"></div>
      </form>
  </div>
</main>
{% endblock %}